### ISSUE TITLE
known good commit?

### ISSUE THREAD

**Issue by dominictarr** [alantech/alan#246]
I managed to get it building, but `make bdd` errors

a sample of the output:
```
Finished in 1736.48 seconds (user 1890.20 seconds, sys 60.14 seconds)
193 examples, 0 failures, 6 pendings


Notable examples: (Listed here do not affect your suite's status)

shellspec spec/006_string_spec.sh:113 # 1) Strings templating runs js PENDING
shellspec spec/006_string_spec.sh:119 # 2) Strings templating runs agc PENDING
shellspec spec/010_object_literal_spec.sh:218 # 3) Object literals map support runs js PENDING
shellspec spec/010_object_literal_spec.sh:224 # 4) Object literals map support runs agc PENDING
shellspec spec/012_hash_spec.sh:205 # 5) Hashing HashMap runs js PENDING
shellspec spec/012_hash_spec.sh:211 # 6) Hashing HashMap runs agc PENDING

Aborted with status code [executor: 0] [reporter: 0] [error handler: 102]
Fatal error occurred, terminated with exit status 102.
make: *** [Makefile:32: bdd] Error 102
```
btw, am on main, commit: `ff7ee9fabfc1d6f0e33a17249656610d12b49a46 `

did it just miss a timeout?

**Comment by dfellis** [comment]
So the 6 pendings all make sense. String templating isn't done, yet, nor the HashMap syntactic sugar.

That does not error out on me, however. Could I see the entire log? Since it's not showing up in the test summary, it sounds like the test system itself errored?

With respect to the question in the title, though, all of the commits on main are "known good commits" since we added CI -- we have been meticulous on keeping it clean and doing the dirty work on branches. However the only two systems we have been testing with CI are Ubuntu Linux and MacOS X. Still working on getting Windows testing working (though that's almost done).

**Comment by dominictarr** [comment]
hmm, okay this Ubuntu 20

output: [output.txt](https://github.com/alantech/alan/files/5152641/output.txt)

**Comment by dfellis** [comment]
You output looks incredibly similar to [this output from CI on the latest commit](https://github.com/alantech/alan/runs/1042382155) except for the exit code.

The two things I noticed:

1. Your path implies Windows Subsystem for Linux, I think? (I'm not sure, though, but having a directory named `c` has a very Cygwin-ish feel.)
2. Your total runtime is twice as slow as the CI's runtime.

A theory around 1: If the project is in an NTFS partition cloned via Git for Windows, but compiled on Ubuntu in the Linux Subsystem, there may be some weirdness around newlines being two characters on Windows and one on Linux and maybe that caused some weird issue not in Alan (since all of the tests passed excluding the 6 pending tests that are known not-done-yet) but in shellspec, the testing environment itself when it tried to collate its results?

A theory on 2: did you happen to abort with Ctrl+C because of the ridiculous test time? Getting it faster is absolutely a goal for us, partly due to issues like this. While perhaps its true that your laptop takes longer to run the code, it could also have gotten "stuck" with the HTTP server tests, since that spawns a background process and then has to clean up after it and is not part of the test reporting itself, so it's possible a Ctrl+C caused it to force the child processes to close and then it could report that it failed because it couldn't actually finish cleaning up normally? This seems far less likely since I would expect you to have told me about it and that child process handling has been pretty stable so far.

**Comment by dominictarr** [comment]
oh no, it's not c for c: it's just c for code. it's git installed with apt. WSL is actually running the linux kernel, I can confirm it does not change the line ending (and I've told my text editor not to add windows endings)

I didn't abort it, i just started it and then did other things. I'll run it again to check...

**Comment by dominictarr** [comment]
same again 
[output.txt](https://github.com/alantech/alan/files/5153892/output.txt)

**Comment by dfellis** [comment]
The test suite issue is confusing and annoying since I use Ubuntu 20.04 as well, but directly instead of in WSL, and it works. It also works in Manjaro Linux for ARM64 and OS X, and I just got compiling and testing directly on Windows working today (confirmed in a Windows 7 VM with Git for Windows + Git Bash and GnuMake for Windows, Node for Windows, Rust for Windows and Yarn for Windows all manually installed, and this also working in a Windows Server 2019 VM in Github Actions. So I still think it's something weird with WSL. :/

However, your output says that the compiler and runtime work. All of the tests that should pass are passing, it's just returning the wrong return code from shellspec *somehow*.

Have you tried using the compiler and runtime you've built against some example source files? Eg `cd compiler && node dist/index.js testfile.ln testfile.agc && ../runtime/target/release/alan-runtime run testfile.agc`?

**Comment by cdmistman** [comment]
triage: there are many known-good commits, @dominictarr if you still experience problems running the test suite feel free to re-open this issue.
