### ISSUE TITLE
how is concurrency implemented?

### ISSUE THREAD

**Issue by dominictarr** [alantech/alan#255]
I wanted to understand how concurrency is implemented. I couldn't find any examples code in the specs that is concurrent, but I found http stuff and I made one.

```
from @std/app import start, print, exit
from @std/http import get

on start {
  print(get('http://example.com'))
  print( get('https://raw.githubusercontent.com/alantech/hellodep/aea1ce817a423d00107577a430a046993e4e6cad/index.ln')) 
  emit exit 0
}
```
running this had a pause before printing the first result and the second, so it didn't seem to be properly concurrent. but I know alan is ment to detect this so I tried another one:

```
from @std/app import start, print, exit
from @std/http import get

on start {

  let a = get('http://example.com')
  let b = get('https://raw.githubusercontent.com/alantech/hellodep/aea1ce817a423d00107577a430a046993e4e6cad/index.ln')
  
  print(a)
  print(b)
  
  emit exit 0
}
```
this ran in consistently less time.
looking at the aga output

this is the series one:
```
handler for _start with size 26
  @0 = httpget(@-1, @0) #0
  @1 = zeroed(@0, @0) #1
  @2 = copybool(@-33, @0) #2
  @3 = isOk(@0, @0) #3
  @5 = condfn(@3, _6ec2a30a_613f_4db5_b167_c5c7b49f2f4c) #4
  @11 = condfn(@2, _5ae34216_1b60_4762_9c25_d2233d6c9d52) #5
  @12 = catstr(@1, @-49) #6
  emit(stdout, @12) #7 <- [#6]
  @13 = httpget(@-65, @0) #8
  @14 = zeroed(@0, @0) #9
  @15 = copybool(@-33, @0) #10
  @16 = isOk(@13, @0) #11
  @18 = condfn(@16, _7cc6ee92_da35_4345_bbc4_53b3d351ed01) #12
  @24 = condfn(@15, _84c67f99_caef_4ab3_a0f0_53ad6e4cdc48) #13
  @25 = catstr(@14, @-49) #14
  emit(stdout, @25) #15 <- [#14]
  emit(exit, @-177) #16
```
this is the concurrent one
```
handler for _start with size 26
  @0 = httpget(@-1, @0) #0
  @1 = httpget(@-33, @0) #1
  @2 = zeroed(@0, @0) #2
  @3 = copybool(@-145, @0) #3
  @4 = isOk(@0, @0) #4
  @6 = condfn(@4, _425dfe48_c585_41ac_a51f_f86106b1845f) #5
  @12 = condfn(@3, _fc051d81_a522_4df1_92d9_cd64c0f24aa3) #6
  @13 = catstr(@2, @-161) #7
  emit(stdout, @13) #8 <- [#7]
  @14 = zeroed(@0, @0) #9
  @15 = copybool(@-145, @0) #10
  @16 = isOk(@1, @0) #11
  @18 = condfn(@16, _64a3b920_0c44_42f1_9a00_7f67c2d11135) #12
  @24 = condfn(@15, _0a64441f_da82_4712_962e_36f0f2f3e817) #13
  @25 = catstr(@14, @-161) #14
  emit(stdout, @25) #15 <- [#14]
  emit(exit, @-177) #16
```

`@<number> = ` seems to be a variable declaration. it always uses a new variable. I'm not sure what `#<number>` means. It might just be a comment?

it looks like it is internally using a promise like model, is it waiting for the second request at `@16 = isOk(@1, @0)` or just at the next op?

I can see that usually it's important that print statements are in the right order, but if assigning the output to vars can make it concurrent, passing the result to functions (without depending on any thing derived from the output of the other) could make it concurrent too...

although I can think of cases where implicit concurrency could cause problems. such as `mkdir foo; echo "hello" > foo/bar.txt` like that, but in a remote http api it may not be clear that foo/bar.txt is created by `mkdir` because it didn't return it.

**Comment by dfellis** [comment]
You've already run into a limitation in our currently primitive concurrency model. We can't go further until [this issue is fixed](https://github.com/alantech/alan/issues/197) because we can't trust the dependency graph in here good enough.

The `#number` stuff is part of the dependency graph stuff. You see sometimes it looks like `#number <- [#othernumber]` Almost all of those lines are *supposed* to have the dependencies declared, but we only have it working for emit statements right now. That's for the dependency graph stuff which we can use for re-ordering.

Since that's not done, yet, we have a simpler form that uses the implicit "fragment boundaries" for reordering. There's basically a few different kinds of opcodes and that `condfn` opcode that does a conditional function call acts as a boundary that we can't merge across because we're currently unsure whether or not that would be a safe behavior.

In the series one, you see the `httpget` calls are separated from each other with a `condfn` call in-between while in the concurrent one they're together (actually already perfectly grouped together in your example).

Once we have the actual graph tracking implemented in the AMM to AGA layer of the compiler, we can do the IO grouping based on the *actual* dependencies involved and in this case note that the first one with the http get calls being nested have no dependencies on anything but constant data and can pull them to the beginning of the handler and call them concurrently.

On other topics:

`@16 = isOk(@1, @0)` *is* just another op. It's a Result<foo> isOk method that checks if the return value was the expected value or an error message. Your musing on async/await is right, but that's not actually represented even in this assembler model, it's completely automatic based on the opcode implementation. In this case `httpget` is the "automatic async/await" opcode.

> although I can think of cases where implicit concurrency could cause problems. such as `mkdir foo; echo "hello" > foo/bar.txt` like that, but in a remote http api it may not be clear that foo/bar.txt is created by `mkdir` because it didn't return it.

This example is true if we implemented it similarly to a shell syntax where `mkdir foo` is purely a side-effect function, but if we require the user to check for an error, we would be able to detect the implicit dependency because you'd only call the `echo "hello" > foo/bar.txt` on the success path (even in the current primitive form, actually, because the success path would be inside of a `condfn` call in a related `closure` block).

**Comment by dominictarr** [comment]
Oh, another question: is there a way to have a race? as in, something that happens after either A or B happens, without waiting for the slow one. For example, in amazon dynamo db, a client requests to 3 servers, and responds when 2 of them return the same response.

one idea how this could be expressed:
```
a = get(a_url)
b = get(b_url)
if(isReady(a) || isReady(b))
  //...
```
for the || (or) expression to be true, you don't need to know the values of both a and b, only one of them. Although, in C like languages (not sure about alan) || doesn't evaluate the right hand side unless necessary. so if `isReady(b)` had side effects then to maintain expected behavior it would need to evaluate `isReady(a)` first.

**Comment by dfellis** [comment]
So because of the *implicit* nature of the async/await IO work in Alan, an `isReady` function would always return `true` because it won't continue this particular thread of execution until the data is there for it.

We have a primitive equivalent to `Promise.all` baked in that we will make more capable in the coming weeks, but [Promise.race](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/race) is incompatible with that.

I need to think on how that could be defined when the language eagerly awaits IO requests right now and since these IO opcodes may be wrapped up in cpu-bound transforms before getting to you with the simple function call. I think it could be done with a new Array-based opcode, but the syntax on your end might be wonky, so it might also make sense to add new syntax to the language to support it (and internally rewrite into the new opcode).

Let me draw up an RFC on this.
