### ISSUE TITLE
Write web server benchmarking

### ISSUE THREAD

**Issue by dfellis** [alantech/alan#263]

**Comment by depombo** [comment]
There is some research to be done here to find out what the best practices are for web server benchmarks and then list them here before actually running them.

**Comment by cdmistman** [comment]
Apache Bench seems to be popular. Here are the Rust web frameworks listed by [arewewebyet](https://www.arewewebyet.org/):
- [actix-web](https://crates.io/crates/actix-web)
- [rocket](https://crates.io/crates/rocket) (note: only available on nightly due to 2 unstable features)
- [warp](https://crates.io/crates/warp)
- [tide](https://crates.io/crates/tide)
- [gotham](https://crates.io/crates/gotham)
- ~[iron](https://crates.io/crates/iron)~ seems inactive based on GitHub activity
- ~[nickel](https://crates.io/crates/nickel)~ same as above
- ~[thruster](https://crates.io/crates/thruster)~ just middleware
