### ISSUE TITLE
make `fork` and `join` cheaper in memcpys by changing the memory model

### ISSUE THREAD

**Issue by depombo** [alantech/alan#356]

**Comment by dfellis** [comment]
![IMG_20201214_133140](https://user-images.githubusercontent.com/765551/102138196-d6424c00-3e10-11eb-9dd1-195cbb1422ea.jpg)

Here's a diagram of how it could work with minimal changes.

The HandlerMemory object has an optional parent pointer `Option<*HandlerMemory>` and the address arrays are now `Vec<Option<(usize, usize)>>`.

Reading data would first check if the optional is defined in the current memory space, otherwise return the parent's memory read (or fail if no parent). Writing data would always write into the current HandlerMemory space.

There would need to be new API work to read from fractal memory (perhaps as an iterator?) because now you can't guarantee that the virtual pointer logic is on the current HandlerMemory or the parent and where you need to read.

If you want to get a mutable version of data in the parent scope, it needs to copy it on the mutable read request so updates work as expected.

This makes `fork` a very cheap object creation, while `join` should be roughly the same complexity, except now it's easier to determine if any particular address was *actually* updated in the fork or not, meaning the guessing logic that was attempted before (and didn't really work) won't be necessary.

There's still the issue of unreachable data not being dropped until the handler finishes running, but for opcodes that are known to not mutate the outer scope (and almost always only return data through the `args` address space) there can be a special, simpler `join_retval` method that only rejoins the return value into the original scope to let the intermediate data die at that point.

**Comment by depombo** [comment]
> There's still the issue of unreachable data not being dropped until the handler finishes running, but for opcodes that are known to not mutate the outer scope (and almost always only return data through the `args` address space) there can be a special, simpler `join_retval` method that only rejoins the return value into the original scope to let the intermediate data die at that point.

Do you mean this https://github.com/alantech/alan/blob/main/avm/src/vm/opcode.rs#L1611?

**Comment by dfellis** [comment]
Yes, exactly. :)
