### ISSUE TITLE
Module-level mutable state which does not give a compilation error

### ISSUE THREAD

**Issue by Ivo-Balbaert** [alantech/alan#366]
Module level variables are forbidden, the following code snippet:
import @std/app

let varnum = 42;

on app.start {
  app.print(varnum);
  emit app.exit 0;
}
gives the compile error: line 3:0 extraneous input 'let' expecting {'import', 'from', 'type', 'fn', 'event', 'on', 'export', 'const', 'prefix', 'infix', 'interface', NEWLINE, WS}

However, the following snippet compiles successfully:
import @std/app

const num = 108;
let varnum = 42;

on app.start {
  app.print(num);
  emit app.exit 0;
}
but when executing seems to make the runtime go asleep without any output.

**Comment by dfellis** [comment]
So somehow the ANTLR grammar is parsing the entirety of the remainder of the file as part of that constant, then the later stage of the compiler sees that the `num` constant is "never used" and never digs into its AST in a way that would trigger that stage of the compiler to emit an error message.

So the only line included in the whole output program is the `import @std/app` line, which causes the AMM representation to become:

```amm
event stdout: string
event exit: int8
event stderr: string
on stdout fn (out: string): void {
  const _f7177e88_d52b_4d55_b7aa_abfcddce607a: void = stdoutp(out)
}
on exit fn (status: int8): void {
  const _fb613609_89d6_4da4_ab9b_86e5329eb362: void = exitop(status)
}
on stderr fn (err: string): void {
  const _e7af125e_86ff_417e_9dd6_1d6895ca824d: void = stderrp(err)
}
```

Only hooks for emitting stdout/stderr/exit events and nothing else, so nothing listens to the start event to kick of action and nothing calls exit, so the program sits there doing nothing.

There is a similar issue to this with the same root cause. Figuring out the ANTLR grammar issue would be good, but I'm also hoping to just eliminate ANTLR from the compiler since that's blocking a lot of optimizations to the compiler that we want to do.

**Comment by Ivo-Balbaert** [comment]
Thanks for the insightful analysis!

**Comment by dfellis** [comment]
This now no longer happens as of 0.1.24, and the new parser, while confused, gives a vague indication of where it thinks the error occurred (we do hope to improve this over time).

```
damocles@Talyn:/usr/local/alancorp/alan/compiler(fix-trailing-whitespace-imports)$ alan compile temp.ln temp.amm
Could not load /usr/local/alancorp/alan/compiler/temp.ln
AST Parse error, cannot continue due to syntax error between line 4:1 - 7:3
```

With line 4 being the start of the invalid `let` statement.
